### ISSUE TITLE
TokenMap value change to None，when using getChild()

### ISSUE THREAD

**Issue by pan-lj** [cparse/cparse#99] opened 2022-11-11 11:40 UTC
<img width="786" alt="image" src="https://user-images.githubusercontent.com/47551508/201643764-5e3e5747-cc63-4d81-bfd1-6b7c0750b965.png">
<img width="280" alt="image" src="https://user-images.githubusercontent.com/47551508/201332271-d2531f63-cf5b-4d50-9c19-c23cd6d2253e.png">
the value in local are all None, but not in scope

the code below is normal:
<img width="735" alt="image" src="https://user-images.githubusercontent.com/47551508/201333144-b0f51ead-d8bc-4963-b7d3-801af9cd4653.png">

**Comment by VinGarcia** [comment] 2022-11-19 02:05
Hey @pan-lj I think this is actually a misunderstanding of how the TokenMap type works. In your example you wrote the following:

```cpp
  // Build the local namespace:
  TokenMap kwargs;
  TokenMap local = scope.getChild();

  for (auto& m : scope.map()) {
    std::cout << "scope-- " << m.first << ": " << m.second << std::endl;
    if (!local.find(m.first)) {
      std::cout << "local-- can not find " + m.first << std::endl;
    } else {
      std::cout << "local-- " << m.first << ": " << local[m.first] << std::endl;
    }
  }
```

But in this code you are ignoring the value returned by `local.find(m.first)` when it is not `null`, but this is actually the value that you want, so instead you should replace the `local[m.first]` with this value when printing, like this:

```cpp
  // Build the local namespace:
  TokenMap kwargs;
  TokenMap local = scope.getChild();

  for (auto& m : scope.map()) {
    std::cout << "scope-- " << m.first << ": " << m.second << std::endl;
    auto value = local.find(m.first);
    if (!value) {
      std::cout << "local-- can not find " + m.first << std::endl;
    } else {
      std::cout << "local-- " << m.first << ": " << *value << std::endl;
    }
  }
```

The TokenMap container allows us to implement a behavior equivalent to JavaScript prototypes, i.e. if TokenMap `C` e child of TokenMap `P` and `P["foo"] = "bar"` then `P.find("foo")` will also return `"bar"`.

This behavior was implemented for two reasons: (1) to allow nested scopes inside the CParse expressions and also (2) for allowing the implementation of a map index builtin operator just like JavaScript's index operator:

https://github.com/cparse/cparse/blob/master/builtin-features/operations.inc#L84-L100

So note that the index operator of the TokenMap class is not meant to work as this CParse operator described above, it only returns the values contained on that map ignoring any parent maps.

I understand that this confusion comes from the fact that we have an index operator for the C++ class and another for the CParse expressions, but what you showed me is actually the intended behavior for the C++ operator.

I hope this explanation helps you implement what you want to implement.

If you think this explanation solves your problem I will close this issue in a couple of days, otherwise, feel free to explain in more detail the problem you are facing.

**Comment by pan-lj** [comment] 2022-11-19 03:00
but when I calculate self define function, it will get error: The Token None is not a string!

**Comment by pan-lj** [comment] 2022-11-19 04:09
thanks for your explanation, if I want to implement the intended behavior for the C++ operator, can I implement operator[] like this:
`packToken& TokenMap::operator[](const std::string& key) {
  if (!parent() || map().find(key) != map().end()) {
    return map()[key];
  }
  return (*parent())[key];
}`

**Comment by VinGarcia** [comment] 2022-11-19 15:03
Yeah on a visual inspection it looks correct. But overwriting these operators usually comes with some surprises, I would recommend writing some tests to be sure it is working as expected, but it looks ok.

**Comment by pan-lj** [comment] 2022-11-20 07:16
Okay, I will test it, thanks.

**Comment by VinGarcia** [comment] 2022-12-13 21:42
So since this is solved I am going to close this one.

Feel free to add a comment here or create a new issue again in the future =]

**Closed by VinGarcia** 2022-12-13 21:42 UTC
