### ISSUE TITLE
Errors with Linux emulator using GCC

### ISSUE THREAD

**Issue by spelsinx** [cparse/cparse#97] opened 2022-10-31 03:57 UTC
Run jspy.cpp:
`~/j $ gcc jspy.cpp
In file included from jspy.cpp:6:
In file included from ./statements.h:6:     ././cparse/shunting-yard.h:268:37: warning: 'const' qualifier on function type 'cparse::rWordParser_t' (aka 'void (const char *, const char **, cparse::rpnBuilder *)') has no effect [-Wignored-qualifiers]
  void add(const std::string& word, const rWordParser_t* parser) {
                                    ^~~~~~
././cparse/shunting-yard.h:273:20: warning: 'const' qualifier on function type 'cparse::rWordParser_t' (aka 'void (const char *, const char **, cparse::rpnBuilder *)') has no effect [-Wignored-qualifiers]
  void add(char c, const rWordParser_t* parser) {
                   ^~~~~~
In file included from jspy.cpp:6:           ./statements.h:15:3: error: unknown type name 'packToken'; did you mean 'cparse::packToken'?
  packToken value;
  ^~~~~~~~~                                   cparse::packToken                         ././cparse/./packToken.h:9:7: note: 'cparse::packToken' declared here
class packToken {
      ^
In file included from jspy.cpp:6:           ./statements.h:19:15: error: unknown type name 'packToken'; did you mean 'cparse::packToken'?
  returnState(packToken value) : type(NORMAL), value(value) {}                                        ^~~~~~~~~                                   cparse::packToken
././cparse/./packToken.h:9:7: note: 'cparse::packToken' declared here
class packToken {
      ^                                     In file included from jspy.cpp:6:
./statements.h:20:39: error: unknown type name 'packToken'; did you mean 'cparse::packToken'?
  returnState(const returnType& type, packToken value, bool value_omitted = true)                                             ^~~~~~~~~
                                      cparse::packToken
././cparse/./packToken.h:9:7: note: 'cparse::packToken' declared here
class packToken {
      ^
In file included from jspy.cpp:6:
./statements.h:17:39: error: use of undeclared identifier 'packToken'; did you mean 'cparse::packToken'?
  returnState() : type(NORMAL), value(packToken::None()) {}
                                      ^~~~~~~~~
                                      cparse::packToken
././cparse/./packToken.h:9:7: note: 'cparse::packToken' declared here                   class packToken {                                 ^
In file included from jspy.cpp:6:
./statements.h:18:59: error: use of undeclared identifier 'packToken'; did you mean 'cparse::packToken'?                              returnState(const returnType& type) : type(type), value(packToken::None()) {}
                                                          ^~~~~~~~~
                                                          cparse::packToken             ././cparse/./packToken.h:9:7: note: 'cparse::packToken' declared here
class packToken {
      ^
In file included from jspy.cpp:6:           ./statements.h:27:25: error: unknown type name 'TokenMap'; did you mean 'cparse::TokenMap'?
                        TokenMap parent_scope) = 0;                                                             ^~~~~~~~
                        cparse::TokenMap
././cparse/./containers.h:66:8: note: 'cparse::TokenMap' declared here
struct TokenMap : public Container<MapData_t>, public Iterable {
       ^
In file included from jspy.cpp:6:
./statements.h:28:29: error: unknown type name 'TokenMap'; did you mean 'cparse::TokenMap'?                                           virtual returnState _exec(TokenMap scope) const = 0;                                                              ^~~~~~~~
                            cparse::TokenMap././cparse/./containers.h:66:8: note: 'cparse::TokenMap' declared here                  struct TokenMap : public Container<MapData_t>, public Iterable {                               ^
In file included from jspy.cpp:6:           ./statements.h:33:16: error: unknown type name 'TokenMap'; did you mean 'cparse::TokenMap'?
               TokenMap parent_scope = &TokenMap::empty) {                                             ^~~~~~~~
               cparse::TokenMap             ././cparse/./containers.h:66:8: note: 'cparse::TokenMap' declared here                  struct TokenMap : public Container<MapData_t>, public Iterable {                               ^                                    In file included from jspy.cpp:6:           ./statements.h:37:20: error: unknown type name 'TokenMap'; did you mean 'cparse::TokenMap'?                                           returnState exec(TokenMap scope) const { return _exec(scope); }
                   ^~~~~~~~                                    cparse::TokenMap
././cparse/./containers.h:66:8: note: 'cparse::TokenMap' declared here
struct TokenMap : public Container<MapData_t>, public Iterable {
       ^                                    In file included from jspy.cpp:6:           ./statements.h:33:41: error: use of undeclared identifier 'TokenMap'; did you mean 'cparse::TokenMap'?
               TokenMap parent_scope = &TokenMap::empty) {
                                        ^~~~~~~~                                                                                cparse::TokenMap                                ././cparse/./containers.h:66:8: note: 'cparse::TokenMap' declared here
struct TokenMap : public Container<MapData_t>, public Iterable {
       ^
In file included from jspy.cpp:6:
./statements.h:50:54: error: unknown type name 'TokenMap'; did you mean 'cparse::TokenMap'?
  void _compile(const char* code, const char** rest, TokenMap parent_scope);
                                                     ^~~~~~~~                                                                                cparse::TokenMap                   ././cparse/./containers.h:66:8: note: 'cparse::TokenMap' declared here
struct TokenMap : public Container<MapData_t>, public Iterable {                               ^                                    In file included from jspy.cpp:6:           ./statements.h:51:21: error: unknown type name 'TokenMap'; did you mean 'cparse::TokenMap'?                                           returnState _exec(TokenMap scope) const;                      ^~~~~~~~                                    cparse::TokenMap        ././cparse/./containers.h:66:8: note: 'cparse::TokenMap' declared here                  struct TokenMap : public Container<MapData_t>, public Iterable {                               ^                                    In file included from jspy.cpp:6:           ./statements.h:56:18: error: unknown type name 'TokenMap'; did you mean 'cparse::TokenMap'?                                                          TokenMap parent_scope = &TokenMap::empty) {                                             ^~~~~~~~                                    cparse::TokenMap           ././cparse/./containers.h:66:8: note: 'cparse::TokenMap' declared here                  struct TokenMap : public Container<MapData_t>, public Iterable {                               ^                                    In file included from jspy.cpp:6:           ./statements.h:60:18: error: unknown type name 'TokenMap'; did you mean 'cparse::TokenMap'?                                                          TokenMap parent_scope = &TokenMap::empty) {                                             ^~~~~~~~                                    cparse::TokenMap           ././cparse/./containers.h:66:8: note: 'cparse::TokenMap' declared here                  struct TokenMap : public Container<MapData_t>, public Iterable {                               ^                                    In file included from jspy.cpp:6:           ./statements.h:56:43: error: use of undeclared identifier 'TokenMap'; did you mean 'cparse::TokenMap'?                                               TokenMap parent_scope = &TokenMap::empty) {                                                                      ^~~~~~~~                                                                                cparse::TokenMap                              ././cparse/./containers.h:66:8: note: 'cparse::TokenMap' declared here                  struct TokenMap : public Container<MapData_t>, public Iterable {                               ^                                    In file included from jspy.cpp:6:           ./statements.h:60:43: error: use of undeclared identifier 'TokenMap'; did you mean 'cparse::TokenMap'?                                               TokenMap parent_scope = &TokenMap::empty) {                                                                      ^~~~~~~~                                                                                cparse::TokenMap                              ././cparse/./containers.h:66:8: note: 'cparse::TokenMap' declared here                  struct TokenMap : public Container<MapData_t>, public Iterable {                               ^                                    In file included from jspy.cpp:6:           ./statements.h:74:3: error: unknown type name 'calculator'; did you mean 'cparse::calculator'?                                        calculator cond;                            ^~~~~~~~~~                                  cparse::calculator                        ././cparse/shunting-yard.h:401:7: note: 'cparse::calculator' declared here
class calculator {
      ^
In file included from jspy.cpp:6:           ./statements.h:79:54: error: unknown type name 'TokenMap'; did you mean 'cparse::TokenMap'?
  void _compile(const char* code, const char** rest, TokenMap parent_scope);                                                                 ^~~~~~~~
                                                     cparse::TokenMap
././cparse/./containers.h:66:8: note: 'cparse::TokenMap' declared here                  struct TokenMap : public Container<MapData_t>, public Iterable {
       ^
In file included from jspy.cpp:6:
./statements.h:80:21: error: unknown type name 'TokenMap'; did you mean 'cparse::TokenMap'?
  returnState _exec(TokenMap scope) const;
                    ^~~~~~~~                                    cparse::TokenMap
././cparse/./containers.h:66:8: note: 'cparse::TokenMap' declared here
struct TokenMap : public Container<MapData_t>, public Iterable {                               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.`

**Comment by VinGarcia** [comment] 2022-10-31 16:24
So, were you trying to compile the JSpy language that I built during my master's degree? It might be better to create a ticket on that project instead:

https://github.com/vinGarcia/jspy

**Comment by spelsinx** [comment] 2022-10-31 20:17
I don't understand what you mean, can you explain better?
I tried to do from the usual example с, the same error.

**Comment by VinGarcia** [comment] 2022-11-01 00:00
`jspy.cpp` is a file from this other project:

https://github.com/VinGarcia/jspy

This file does not exist on https://github.com/cparse/cparse, so I am wondering what steps led you to try to compile that other file.

**Comment by VinGarcia** [comment] 2022-11-01 00:02
Now that I am thinking more about it, I think one of the examples did make a reference to that file, maybe that is what you did. But if you can give me more details of what led you to this compilation error it would be helpful. (and yeah even if this is a problem with that other project I need to do something, either remove this reference from the documentation of this project or fix that problem on the other repository)

**Comment by spelsinx** [comment] 2022-11-02 19:10
I didn't do anything to cause the error to appear. I have tried running cparse and jspy.cpp with the same errors when running them. I'm using Termux - Linux emulator for android. Based on the errors that I threw, I tried to add:
using cparse::TokenMap, using cparse::packToken, and I immediately got some C++ errors there, in short - garbage was displayed. And believe me - I set up the paths correctly and everything else.

**Comment by VinGarcia** [comment] 2022-11-02 19:25
Hello @spelsinx, I am not blaming you or anything like that.

It is probably your first time submitting an issue in an open-source project, so there are some guidelines on how to do that, the main thing is that I don't have a lot of time to investigate these issues since I am not paid for it, so I need as much help from you as possible.

So, the first thing that is important when creating these issues is to include as much information as you can about what steps you went through that resulted in the error you are seeing.

Because when I just compile it on my machine it works.

Things that you can share with me so I can better understand the problem and hopefully reproduce it on my own environment:

1. The environment you are trying to compile it. It looks like it is Termux which is helpful, thank you.
2. What are the exact commands you used? You first cloned the JSpy project and then executed `make`? Can you copy-paste these commands here?
3. What was the exact documentation that you were following when you found this issue?

I am asking these questions so I can try to reproduce the problem on my own environment and then fix it or at least help you fix it on your own environment.

**Comment by spelsinx** [comment] 2022-11-02 19:39
If anything, I use a translator.

1. I am using Termux emulator in Android environment.
2. Commands that I used:
     1. git clone https://github.com/cparse/cparse
     2. cd parse
     3. make
And the errors that I threw in the first message were highlighted, that is, like jSpy.cpp
3. I didn't use the documentation.

**Comment by spelsinx** [comment] 2022-11-02 20:02
For example when I use "make shell" from https://github.com/VinGarcia/jSpy the same errors are shown as in the first message.

**Comment by VinGarcia** [comment] 2022-11-02 20:17
Yeah, the strange thing about it is that I did not expect cparse to have any dependency with jspy, so I am confused about how that error message included the name jspy.cpp

**Comment by VinGarcia** [comment] 2022-11-02 22:14
One question this error message you send, was when you were compiling the cparse project or the jspy project?

**Comment by VinGarcia** [comment] 2022-11-02 22:20
Just so you know I only stopped working for now, so I am starting to investigate it now.

**Comment by spelsinx** [comment] 2022-11-02 22:43
> 

errors occur in both scripts :(

**Comment by spelsinx** [comment] 2022-11-02 22:43
> Just so you know I only stopped working now, so I am starting to investigate it now.

Oh, ok

**Comment by VinGarcia** [comment] 2022-11-02 22:48
I need the errors that happen on cparse, I am not even sure whether jspy is still working, it was a long time ago.

**Comment by VinGarcia** [comment] 2022-11-02 22:49
And it was not ready to be used outside of the scope of my Master's, so it is at most an example of how it can be used. What you really need to compile is just cparse.

**Comment by VinGarcia** [comment] 2022-11-02 23:52
Just to make it clear: I won't try to figure out what is going on with JSpy because the real problem is on CParse. If I start investigating JSpy I might end up fixing several problems unrelated to what is really preventing you from using it, and since my time is limited it would not be ideal.

**Comment by spelsinx** [comment] 2022-11-03 09:03
> I need the errors that happen on cparse, I am not even sure whether jspy is still working, it was a long time ago.

Yes, I already told you, and threw that the errors are the same, the same.

**Comment by VinGarcia** [comment] 2022-11-04 13:11
So, really can't see how that output would come from CParse. If you search in the code there is not reference at all to `jspy` even if you search for it in a case-insensitive way:

```
cd cparse
git grep -i jspy
```

There is also no file named `jspy.cpp` in this project, you can check that using find:

```
cd cparse
find . -name jspy.cpp
```

So I cannot investigate based on the output you sent me because it is not from the CParse project. Can you please rerun this test on CParse and share the output of that command with me? Please erase any directory named jspy from your system as that is another project.

**Comment by VinGarcia** [comment] 2022-11-19 02:05
Ok, I will close this ticket for now, if you want you can reopen it.

**Closed by VinGarcia** 2022-11-19 02:05 UTC

**Comment by spelsinx** [comment] 2022-11-19 13:43
The problem is solved, I indicated this declaration in all the files mentioned above in the error:
``using namespace cparse;```.
As well as I compiled cparse.

**Comment by VinGarcia** [comment] 2022-11-19 15:07
Hehe, I am glad to hear it worked.

Feel free to open more tickets if you have any further issues. I just didn't investigate this one because the error message was mentioning files from another project and I would have no way to know whether the issue described in this error message was related to CParse, and if it was not I would have to do the investigation twice.
